# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\plugin_drvi\agirisk_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1070, 780)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("*{\n"
"    font: 10 px \"Arial\";\n"
"    background-color: rgb(255,255,255);\n"
"    color:black;\n"
"}\n"
"\n"
"QToolButton{\n"
"    border: 1px solid rgb(125,254,23);\n"
"    background-color:  rgb(125,251,140);\n"
"    border-radius: 10px;\n"
"    box-shadow: 6px 6px 2px black\n"
"}\n"
"\n"
"QTextEdit{\n"
"    border: 1px solid red;\n"
"    background-color: white;\n"
"    color: red;\n"
"    cursor: wait;\n"
"    text-shadow: 5px 5px 2px blue;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_body = QtWidgets.QWidget(Dialog)
        self.main_body.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_body.setObjectName("main_body")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_menu = QtWidgets.QWidget(self.main_body)
        self.top_menu.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color:  rgb(41,37,116);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font: 11px \'Arial\';\n"
"    font-weight: bold;\n"
"    word-wrap: normal;\n"
"}")
        self.top_menu.setObjectName("top_menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_menu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_accueil = QtWidgets.QPushButton(self.top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_accueil.sizePolicy().hasHeightForWidth())
        self.menu_accueil.setSizePolicy(sizePolicy)
        self.menu_accueil.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_accueil.setObjectName("menu_accueil")
        self.horizontalLayout.addWidget(self.menu_accueil)
        self.menu_terr_etude = QtWidgets.QPushButton(self.top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_terr_etude.sizePolicy().hasHeightForWidth())
        self.menu_terr_etude.setSizePolicy(sizePolicy)
        self.menu_terr_etude.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_terr_etude.setObjectName("menu_terr_etude")
        self.horizontalLayout.addWidget(self.menu_terr_etude)
        self.menu_choix_indic = QtWidgets.QPushButton(self.top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_choix_indic.sizePolicy().hasHeightForWidth())
        self.menu_choix_indic.setSizePolicy(sizePolicy)
        self.menu_choix_indic.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_choix_indic.setObjectName("menu_choix_indic")
        self.horizontalLayout.addWidget(self.menu_choix_indic)
        self.menu_moda_calcul = QtWidgets.QPushButton(self.top_menu)
        self.menu_moda_calcul.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_moda_calcul.sizePolicy().hasHeightForWidth())
        self.menu_moda_calcul.setSizePolicy(sizePolicy)
        self.menu_moda_calcul.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_moda_calcul.setObjectName("menu_moda_calcul")
        self.horizontalLayout.addWidget(self.menu_moda_calcul)
        self.menu_diag = QtWidgets.QPushButton(self.top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_diag.sizePolicy().hasHeightForWidth())
        self.menu_diag.setSizePolicy(sizePolicy)
        self.menu_diag.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.menu_diag.setObjectName("menu_diag")
        self.horizontalLayout.addWidget(self.menu_diag)
        self.menu_actions_reduc = QtWidgets.QPushButton(self.top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_actions_reduc.sizePolicy().hasHeightForWidth())
        self.menu_actions_reduc.setSizePolicy(sizePolicy)
        self.menu_actions_reduc.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_actions_reduc.setObjectName("menu_actions_reduc")
        self.horizontalLayout.addWidget(self.menu_actions_reduc)
        self.menu_suivi_actions = QtWidgets.QPushButton(self.top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_suivi_actions.sizePolicy().hasHeightForWidth())
        self.menu_suivi_actions.setSizePolicy(sizePolicy)
        self.menu_suivi_actions.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_suivi_actions.setObjectName("menu_suivi_actions")
        self.horizontalLayout.addWidget(self.menu_suivi_actions)
        self.menu_aide = QtWidgets.QPushButton(self.top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_aide.sizePolicy().hasHeightForWidth())
        self.menu_aide.setSizePolicy(sizePolicy)
        self.menu_aide.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_aide.setObjectName("menu_aide")
        self.horizontalLayout.addWidget(self.menu_aide)
        self.verticalLayout_3.addWidget(self.top_menu)
        self.central_container = QtWidgets.QWidget(self.main_body)
        self.central_container.setObjectName("central_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.onglets = QtWidgets.QStackedWidget(self.central_container)
        self.onglets.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.onglets.setAcceptDrops(False)
        self.onglets.setStyleSheet("QStackedWidget{\n"
"    border:none\n"
"}")
        self.onglets.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.onglets.setFrameShape(QtWidgets.QFrame.Box)
        self.onglets.setFrameShadow(QtWidgets.QFrame.Plain)
        self.onglets.setLineWidth(1)
        self.onglets.setObjectName("onglets")
        self.onglet1_accueil = QtWidgets.QWidget()
        self.onglet1_accueil.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QWidget#onglet1_accueil{\n"
"    background-image: url(:/plugins/plugin_agirisk/medias/fleches.png);\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.55, radius:0.45, fx:0.5, fy:0.5, stop:0.0150754 rgba(252, 232, 227, 255), stop:0.61809 rgba(252, 232, 227, 255), stop:1 rgba(252, 252, 252, 0));\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    background-color:  rgb(41,37,116);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    word-wrap: normal;\n"
"    font: 10px \"Arial\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 11px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.34 rgba(251, 251, 251, 0), stop:0.341 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}")
        self.onglet1_accueil.setObjectName("onglet1_accueil")
        self.gpe_etape1 = QtWidgets.QWidget(self.onglet1_accueil)
        self.gpe_etape1.setGeometry(QtCore.QRect(50, 410, 181, 201))
        self.gpe_etape1.setStyleSheet("")
        self.gpe_etape1.setObjectName("gpe_etape1")
        self.label_6 = QtWidgets.QLabel(self.gpe_etape1)
        self.label_6.setGeometry(QtCore.QRect(0, 40, 181, 20))
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.accueil_terr_etude = QtWidgets.QPushButton(self.gpe_etape1)
        self.accueil_terr_etude.setGeometry(QtCore.QRect(50, 5, 121, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accueil_terr_etude.sizePolicy().hasHeightForWidth())
        self.accueil_terr_etude.setSizePolicy(sizePolicy)
        self.accueil_terr_etude.setObjectName("accueil_terr_etude")
        self.pb_etape3_3 = QtWidgets.QPushButton(self.gpe_etape1)
        self.pb_etape3_3.setGeometry(QtCore.QRect(8, 8, 26, 26))
        self.pb_etape3_3.setStyleSheet("width: 26px;\n"
"height: 26px;\n"
"border : 1 px solid red;\n"
"background-color: rgb(239, 120, 88);\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"color: white;\n"
"border-radius: 13px;")
        self.pb_etape3_3.setObjectName("pb_etape3_3")
        self.widget_7 = QtWidgets.QWidget(self.gpe_etape1)
        self.widget_7.setGeometry(QtCore.QRect(10, 70, 161, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setStyleSheet("image: url(:/plugins/plugin_agirisk/medias/territoiresfr.png);")
        self.widget_7.setObjectName("widget_7")
        self.gpe_etape2 = QtWidgets.QWidget(self.onglet1_accueil)
        self.gpe_etape2.setGeometry(QtCore.QRect(200, 160, 181, 211))
        self.gpe_etape2.setObjectName("gpe_etape2")
        self.label_7 = QtWidgets.QLabel(self.gpe_etape2)
        self.label_7.setGeometry(QtCore.QRect(0, 40, 181, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.accueil_choix_indic = QtWidgets.QPushButton(self.gpe_etape2)
        self.accueil_choix_indic.setEnabled(True)
        self.accueil_choix_indic.setGeometry(QtCore.QRect(50, 5, 121, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accueil_choix_indic.sizePolicy().hasHeightForWidth())
        self.accueil_choix_indic.setSizePolicy(sizePolicy)
        self.accueil_choix_indic.setMaximumSize(QtCore.QSize(150, 16777215))
        self.accueil_choix_indic.setObjectName("accueil_choix_indic")
        self.pb_etape3_2 = QtWidgets.QPushButton(self.gpe_etape2)
        self.pb_etape3_2.setGeometry(QtCore.QRect(8, 8, 26, 26))
        self.pb_etape3_2.setStyleSheet("width: 26px;\n"
"height: 26px;\n"
"border : 1 px solid red;\n"
"background-color: rgb(239, 120, 88);\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"color: white;\n"
"border-radius: 13px;")
        self.pb_etape3_2.setObjectName("pb_etape3_2")
        self.widget_6 = QtWidgets.QWidget(self.gpe_etape2)
        self.widget_6.setGeometry(QtCore.QRect(10, 80, 161, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("image: url(:/plugins/plugin_agirisk/medias/personnalisation.png);")
        self.widget_6.setObjectName("widget_6")
        self.gpe_etape3 = QtWidgets.QWidget(self.onglet1_accueil)
        self.gpe_etape3.setGeometry(QtCore.QRect(530, 170, 231, 151))
        self.gpe_etape3.setObjectName("gpe_etape3")
        self.label_8 = QtWidgets.QLabel(self.gpe_etape3)
        self.label_8.setGeometry(QtCore.QRect(0, 40, 231, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.accueil_diag = QtWidgets.QPushButton(self.gpe_etape3)
        self.accueil_diag.setGeometry(QtCore.QRect(49, 5, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accueil_diag.sizePolicy().hasHeightForWidth())
        self.accueil_diag.setSizePolicy(sizePolicy)
        self.accueil_diag.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.accueil_diag.setObjectName("accueil_diag")
        self.pb_etape3 = QtWidgets.QPushButton(self.gpe_etape3)
        self.pb_etape3.setGeometry(QtCore.QRect(8, 8, 26, 26))
        self.pb_etape3.setStyleSheet("width: 26px;\n"
"height: 26px;\n"
"border : 1 px solid red;\n"
"background-color: rgb(239, 120, 88);\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"color: white;\n"
"border-radius: 13px;")
        self.pb_etape3.setObjectName("pb_etape3")
        self.widget_5 = QtWidgets.QWidget(self.gpe_etape3)
        self.widget_5.setGeometry(QtCore.QRect(10, 70, 211, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("image: url(:/plugins/plugin_agirisk/medias/analyse.png);")
        self.widget_5.setObjectName("widget_5")
        self.gpe_etape4 = QtWidgets.QWidget(self.onglet1_accueil)
        self.gpe_etape4.setEnabled(True)
        self.gpe_etape4.setGeometry(QtCore.QRect(800, 410, 181, 211))
        self.gpe_etape4.setObjectName("gpe_etape4")
        self.label_9 = QtWidgets.QLabel(self.gpe_etape4)
        self.label_9.setGeometry(QtCore.QRect(0, 40, 181, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.accueil_actions_reduc = QtWidgets.QPushButton(self.gpe_etape4)
        self.accueil_actions_reduc.setEnabled(True)
        self.accueil_actions_reduc.setGeometry(QtCore.QRect(49, 5, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accueil_actions_reduc.sizePolicy().hasHeightForWidth())
        self.accueil_actions_reduc.setSizePolicy(sizePolicy)
        self.accueil_actions_reduc.setMaximumSize(QtCore.QSize(150, 16777215))
        self.accueil_actions_reduc.setObjectName("accueil_actions_reduc")
        self.widget_11 = QtWidgets.QWidget(self.gpe_etape4)
        self.widget_11.setGeometry(QtCore.QRect(0, 80, 181, 131))
        self.widget_11.setStyleSheet("image: url(:/plugins/plugin_agirisk/medias/action.gif);")
        self.widget_11.setObjectName("widget_11")
        self.pb_etape4 = QtWidgets.QPushButton(self.gpe_etape4)
        self.pb_etape4.setGeometry(QtCore.QRect(8, 8, 26, 26))
        self.pb_etape4.setStyleSheet("width: 26px;\n"
"height: 26px;\n"
"border : 1 px solid red;\n"
"background-color: rgb(239, 120, 88);\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"color: white;\n"
"border-radius: 13px;")
        self.pb_etape4.setObjectName("pb_etape4")
        self.gpe_etape5 = QtWidgets.QWidget(self.onglet1_accueil)
        self.gpe_etape5.setEnabled(True)
        self.gpe_etape5.setGeometry(QtCore.QRect(300, 440, 181, 211))
        self.gpe_etape5.setStyleSheet("")
        self.gpe_etape5.setObjectName("gpe_etape5")
        self.widget_15 = QtWidgets.QWidget(self.gpe_etape5)
        self.widget_15.setGeometry(QtCore.QRect(0, 0, 181, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setObjectName("widget_15")
        self.accueil_suivi_actions = QtWidgets.QPushButton(self.widget_15)
        self.accueil_suivi_actions.setEnabled(True)
        self.accueil_suivi_actions.setGeometry(QtCore.QRect(49, 5, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accueil_suivi_actions.sizePolicy().hasHeightForWidth())
        self.accueil_suivi_actions.setSizePolicy(sizePolicy)
        self.accueil_suivi_actions.setMaximumSize(QtCore.QSize(150, 16777215))
        self.accueil_suivi_actions.setObjectName("accueil_suivi_actions")
        self.pb_etape5 = QtWidgets.QPushButton(self.widget_15)
        self.pb_etape5.setGeometry(QtCore.QRect(8, 8, 26, 26))
        self.pb_etape5.setStyleSheet("width: 26px;\n"
"height: 26px;\n"
"border : 1 px solid red;\n"
"background-color: rgb(239, 120, 88);\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"color: white;\n"
"border-radius: 13px;")
        self.pb_etape5.setObjectName("pb_etape5")
        self.label_10 = QtWidgets.QLabel(self.gpe_etape5)
        self.label_10.setGeometry(QtCore.QRect(0, 40, 181, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.widget_4 = QtWidgets.QWidget(self.gpe_etape5)
        self.widget_4.setGeometry(QtCore.QRect(10, 80, 161, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("image: url(:/plugins/plugin_agirisk/medias/suivi.gif);")
        self.widget_4.setObjectName("widget_4")
        self.pb_lien_site_cerema = QtWidgets.QPushButton(self.onglet1_accueil)
        self.pb_lien_site_cerema.setGeometry(QtCore.QRect(10, 10, 301, 81))
        self.pb_lien_site_cerema.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/plugin_agirisk/medias/Logo_RF_Cerema_horizontal.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_lien_site_cerema.setIcon(icon)
        self.pb_lien_site_cerema.setIconSize(QtCore.QSize(301, 81))
        self.pb_lien_site_cerema.setObjectName("pb_lien_site_cerema")
        self.pb_lien_site_agirisk = QtWidgets.QPushButton(self.onglet1_accueil)
        self.pb_lien_site_agirisk.setGeometry(QtCore.QRect(850, 10, 201, 81))
        self.pb_lien_site_agirisk.setStyleSheet("image: url(:/plugins/plugin_agirisk/medias/Logo AgiRiskHD.png);\n"
"background-color: rgb(255, 255, 255);")
        self.pb_lien_site_agirisk.setText("")
        self.pb_lien_site_agirisk.setIconSize(QtCore.QSize(191, 71))
        self.pb_lien_site_agirisk.setObjectName("pb_lien_site_agirisk")
        self.label_21 = QtWidgets.QLabel(self.onglet1_accueil)
        self.label_21.setGeometry(QtCore.QRect(460, 280, 374, 350))
        self.label_21.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/plugins/plugin_agirisk/medias/PhotoCrueNemoursArnaudBouissouTerra.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_21.raise_()
        self.gpe_etape1.raise_()
        self.gpe_etape2.raise_()
        self.pb_lien_site_cerema.raise_()
        self.pb_lien_site_agirisk.raise_()
        self.gpe_etape3.raise_()
        self.gpe_etape4.raise_()
        self.gpe_etape5.raise_()
        self.onglets.addWidget(self.onglet1_accueil)
        self.onglet2_terr_etude = QtWidgets.QWidget()
        self.onglet2_terr_etude.setStyleSheet("QGroupBox{\n"
"    border:none;\n"
"    background-color: white;\n"
"    font: 14px \'Arial\';\n"
"    font-weight: bold;\n"
"    color: rgb(239, 120, 88);\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.54 rgba(251, 251, 251, 0), stop:0.541 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(251, 212, 81, 255);\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);    \n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgba(249,191,144,255);\n"
"    border-radius: 3px;\n"
"    border:2px outset rgb(239, 120, 88);\n"
"    color: rgba(41, 37, 116, 255);\n"
"    font: 11px \"Arial\";\n"
"    font-weight: bold;\n"
"}")
        self.onglet2_terr_etude.setObjectName("onglet2_terr_etude")
        self.gb_terr_etude = QtWidgets.QGroupBox(self.onglet2_terr_etude)
        self.gb_terr_etude.setGeometry(QtCore.QRect(10, 10, 1050, 700))
        self.gb_terr_etude.setStyleSheet("")
        self.gb_terr_etude.setObjectName("gb_terr_etude")
        self.cbox_terr_etude = QtWidgets.QComboBox(self.gb_terr_etude)
        self.cbox_terr_etude.setGeometry(QtCore.QRect(100, 60, 400, 20))
        self.cbox_terr_etude.setAutoFillBackground(False)
        self.cbox_terr_etude.setEditable(False)
        self.cbox_terr_etude.setMaxVisibleItems(20)
        self.cbox_terr_etude.setObjectName("cbox_terr_etude")
        self.cbox_terr_etude.addItem("")
        self.gb_emprise_carto = QtWidgets.QGroupBox(self.gb_terr_etude)
        self.gb_emprise_carto.setGeometry(QtCore.QRect(20, 140, 1010, 540))
        self.gb_emprise_carto.setObjectName("gb_emprise_carto")
        self.carte_territoire = QgsMapCanvas(self.gb_emprise_carto)
        self.carte_territoire.setGeometry(QtCore.QRect(0, 0, 1010, 540))
        self.carte_territoire.setStyleSheet("QgsMapCanvas{\n"
"    border:none;\n"
"}")
        self.carte_territoire.setObjectName("carte_territoire")
        self.selection_territoire_etude = QtWidgets.QPushButton(self.gb_terr_etude)
        self.selection_territoire_etude.setGeometry(QtCore.QRect(20, 90, 130, 20))
        self.selection_territoire_etude.setObjectName("selection_territoire_etude")
        self.lbl_choix_terr_etude_2 = QtWidgets.QLabel(self.gb_terr_etude)
        self.lbl_choix_terr_etude_2.setGeometry(QtCore.QRect(550, 60, 90, 20))
        self.lbl_choix_terr_etude_2.setObjectName("lbl_choix_terr_etude_2")
        self.cbox_couche_alea = QtWidgets.QComboBox(self.gb_terr_etude)
        self.cbox_couche_alea.setGeometry(QtCore.QRect(640, 60, 350, 20))
        self.cbox_couche_alea.setAutoFillBackground(False)
        self.cbox_couche_alea.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.cbox_couche_alea.setEditable(False)
        self.cbox_couche_alea.setDuplicatesEnabled(False)
        self.cbox_couche_alea.setObjectName("cbox_couche_alea")
        self.cbox_couche_alea.addItem("")
        self.cbox_couche_alea.addItem("")
        self.cbox_couche_alea.addItem("")
        self.lbl_choix_terr_etude = QtWidgets.QLabel(self.gb_terr_etude)
        self.lbl_choix_terr_etude.setGeometry(QtCore.QRect(20, 60, 80, 20))
        self.lbl_choix_terr_etude.setObjectName("lbl_choix_terr_etude")
        self.cbox_type_alea = QtWidgets.QComboBox(self.gb_terr_etude)
        self.cbox_type_alea.setGeometry(QtCore.QRect(640, 30, 350, 20))
        self.cbox_type_alea.setAutoFillBackground(False)
        self.cbox_type_alea.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.cbox_type_alea.setEditable(False)
        self.cbox_type_alea.setDuplicatesEnabled(False)
        self.cbox_type_alea.setObjectName("cbox_type_alea")
        self.cbox_type_alea.addItem("")
        self.cbox_type_alea.addItem("")
        self.cbox_type_alea.addItem("")
        self.lbl_choix_type_alea = QtWidgets.QLabel(self.gb_terr_etude)
        self.lbl_choix_type_alea.setGeometry(QtCore.QRect(550, 30, 90, 20))
        self.lbl_choix_type_alea.setObjectName("lbl_choix_type_alea")
        self.selection_alea = QtWidgets.QPushButton(self.gb_terr_etude)
        self.selection_alea.setGeometry(QtCore.QRect(550, 90, 150, 20))
        self.selection_alea.setObjectName("selection_alea")
        self.onglets.addWidget(self.onglet2_terr_etude)
        self.onglet3_choix_indicateurs = QtWidgets.QWidget()
        self.onglet3_choix_indicateurs.setStyleSheet("*{\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    border:none;\n"
"    background-color: white;\n"
"    font: 14px \'Arial\';\n"
"    font-weight: bold;\n"
"    color: rgb(239, 120, 88);\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.54 rgba(251, 251, 251, 0), stop:0.541 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(251, 212, 81, 255);\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);    \n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgba(249,191,144,255);\n"
"    border-radius: 3px;\n"
"    border:2px outset rgb(239, 120, 88);\n"
"    color: rgba(41, 37, 116, 255);\n"
"    font: 11px \"Arial\";\n"
"    font-weight: bold;\n"
"    margin-left: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border:2px inset rgb(239, 120, 88);\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.54 rgba(251, 251, 251, 0), stop:0.541 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}\n"
"\n"
"\n"
"QRadioButtfon {\n"
"    background-color: rgb(252,254,252);\n"
"    color: black;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{ \n"
"    border: 1px solid; \n"
"    border-color: rgb(239, 120, 88);\n"
"    border-radius: 5px;\n"
"    background-color: white; \n"
"    width: 11px; \n"
"    height: 11px; \n"
"}\n"
"\n"
"QRadioButton::indicator::checked{ \n"
"    border: 3px solid; \n"
"    border-color: white;\n"
"    border-radius: 6px;\n"
"    background-color: rgba(41, 37, 116, 255);\n"
"    width: 7px; \n"
"    height: 7px; \n"
"}\n"
"\n"
"QCheckBox:pressed{\n"
"    border:2px inset rgb(239, 120, 88);\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.54 rgba(251, 251, 251, 0), stop:0.541 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked{ \n"
"    border: 1px solid; \n"
"    border-color: rgb(239, 120, 88);\n"
"    border-radius: 1px;\n"
"    background-color: white; \n"
"    width: 11px; \n"
"    height: 11px; \n"
"}\n"
"\n"
"QCheckBox::indicator::checked{ \n"
"    border: 3px solid; \n"
"    border-color: white;\n"
"    border-radius: 1px;\n"
"    background-color: rgba(41, 37, 116, 255);\n"
"    width: 7px; \n"
"    height: 7px; \n"
"}")
        self.onglet3_choix_indicateurs.setObjectName("onglet3_choix_indicateurs")
        self.gb_choix_pt_de_vue = QtWidgets.QGroupBox(self.onglet3_choix_indicateurs)
        self.gb_choix_pt_de_vue.setGeometry(QtCore.QRect(40, 20, 450, 200))
        self.gb_choix_pt_de_vue.setObjectName("gb_choix_pt_de_vue")
        self.rb_parent_pt_vue = QtWidgets.QWidget(self.gb_choix_pt_de_vue)
        self.rb_parent_pt_vue.setGeometry(QtCore.QRect(20, 20, 301, 171))
        self.rb_parent_pt_vue.setObjectName("rb_parent_pt_vue")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rb_parent_pt_vue)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_liste_pts_vue = QtWidgets.QVBoxLayout()
        self.layout_liste_pts_vue.setSpacing(16)
        self.layout_liste_pts_vue.setObjectName("layout_liste_pts_vue")
        self.pb_nvelle_arborescence = QtWidgets.QPushButton(self.rb_parent_pt_vue)
        self.pb_nvelle_arborescence.setObjectName("pb_nvelle_arborescence")
        self.layout_liste_pts_vue.addWidget(self.pb_nvelle_arborescence)
        self.verticalLayout_4.addLayout(self.layout_liste_pts_vue)
        self.gb_thematiques = QtWidgets.QGroupBox(self.onglet3_choix_indicateurs)
        self.gb_thematiques.setGeometry(QtCore.QRect(600, 20, 401, 200))
        self.gb_thematiques.setObjectName("gb_thematiques")
        self.pb_valider_thematiques = QtWidgets.QPushButton(self.gb_thematiques)
        self.pb_valider_thematiques.setGeometry(QtCore.QRect(310, 30, 93, 28))
        self.pb_valider_thematiques.setObjectName("pb_valider_thematiques")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gb_thematiques)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 205, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vl_thematiques = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vl_thematiques.setContentsMargins(0, 0, 0, 0)
        self.vl_thematiques.setObjectName("vl_thematiques")
        self.chkb_gestion_crise = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkb_gestion_crise.setObjectName("chkb_gestion_crise")
        self.vl_thematiques.addWidget(self.chkb_gestion_crise)
        self.chkb_amenagt_terr = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkb_amenagt_terr.setObjectName("chkb_amenagt_terr")
        self.vl_thematiques.addWidget(self.chkb_amenagt_terr)
        self.chkb_act_economique = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkb_act_economique.setObjectName("chkb_act_economique")
        self.vl_thematiques.addWidget(self.chkb_act_economique)
        self.chkb_environnement = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkb_environnement.setObjectName("chkb_environnement")
        self.vl_thematiques.addWidget(self.chkb_environnement)
        self.gb_choix_indic = QtWidgets.QGroupBox(self.onglet3_choix_indicateurs)
        self.gb_choix_indic.setGeometry(QtCore.QRect(40, 240, 1000, 470))
        self.gb_choix_indic.setObjectName("gb_choix_indic")
        self.w_arbo_indicateurs_parent = QtWidgets.QWidget(self.gb_choix_indic)
        self.w_arbo_indicateurs_parent.setGeometry(QtCore.QRect(10, 20, 980, 440))
        self.w_arbo_indicateurs_parent.setObjectName("w_arbo_indicateurs_parent")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.w_arbo_indicateurs_parent)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.w_arbo_indicateurs_parent)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 440))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_4.addWidget(self.widget_14)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.pb_indic_retenu = QtWidgets.QPushButton(self.gb_choix_indic)
        self.pb_indic_retenu.setGeometry(QtCore.QRect(210, 1, 80, 15))
        self.pb_indic_retenu.setStyleSheet("background-color: rgb(96, 180, 103);\n"
"border: none;\n"
"border-radius: 2px; \n"
"color:white;\n"
"margin:0px;\n"
"padding:0px; \n"
"margin-top:1px")
        self.pb_indic_retenu.setObjectName("pb_indic_retenu")
        self.pb_indic_ecarte = QtWidgets.QPushButton(self.gb_choix_indic)
        self.pb_indic_ecarte.setGeometry(QtCore.QRect(300, 1, 80, 15))
        self.pb_indic_ecarte.setStyleSheet("background-color: #f2f2f2;\n"
"border: none;\n"
"border-radius: 2px; \n"
"color: #969696;\n"
"margin:0px;\n"
"padding:0px; \n"
"margin-top:1px")
        self.pb_indic_ecarte.setObjectName("pb_indic_ecarte")
        self.onglets.addWidget(self.onglet3_choix_indicateurs)
        self.onglet4_moda_calcul = QtWidgets.QWidget()
        self.onglet4_moda_calcul.setObjectName("onglet4_moda_calcul")
        self.widget = QtWidgets.QWidget(self.onglet4_moda_calcul)
        self.widget.setGeometry(QtCore.QRect(893, 515, 121, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.te_notice_indicateurs_2 = QtWidgets.QTextEdit(self.widget)
        self.te_notice_indicateurs_2.setObjectName("te_notice_indicateurs_2")
        self.verticalLayout_7.addWidget(self.te_notice_indicateurs_2)
        self.te_notice_indicateurs_5 = QtWidgets.QTextEdit(self.widget)
        self.te_notice_indicateurs_5.setObjectName("te_notice_indicateurs_5")
        self.verticalLayout_7.addWidget(self.te_notice_indicateurs_5)
        self.te_notice_indicateurs_3 = QtWidgets.QTextEdit(self.widget)
        self.te_notice_indicateurs_3.setObjectName("te_notice_indicateurs_3")
        self.verticalLayout_7.addWidget(self.te_notice_indicateurs_3)
        self.gb_mise_en_forme_resultats_3 = QtWidgets.QGroupBox(self.onglet4_moda_calcul)
        self.gb_mise_en_forme_resultats_3.setGeometry(QtCore.QRect(40, 540, 831, 141))
        self.gb_mise_en_forme_resultats_3.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    background-color: rgb(177, 177, 177);\n"
"    font-weight: bold;\n"
"    text-align:center;\n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QComboBox{\n"
"    color:black;\n"
"}\n"
"")
        self.gb_mise_en_forme_resultats_3.setObjectName("gb_mise_en_forme_resultats_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gb_mise_en_forme_resultats_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_13 = QtWidgets.QWidget(self.gb_mise_en_forme_resultats_3)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cb_millesime_gpu = QtWidgets.QComboBox(self.widget_13)
        self.cb_millesime_gpu.setObjectName("cb_millesime_gpu")
        self.gridLayout_4.addWidget(self.cb_millesime_gpu, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_13)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 3, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_13)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 8, 3, 1, 1)
        self.cb_millesime_rpg = QtWidgets.QComboBox(self.widget_13)
        self.cb_millesime_rpg.setObjectName("cb_millesime_rpg")
        self.gridLayout_4.addWidget(self.cb_millesime_rpg, 2, 4, 1, 1)
        self.cb_millesime_bdtopo = QtWidgets.QComboBox(self.widget_13)
        self.cb_millesime_bdtopo.setObjectName("cb_millesime_bdtopo")
        self.gridLayout_4.addWidget(self.cb_millesime_bdtopo, 3, 4, 1, 1)
        self.cb_millesime_sirene = QtWidgets.QComboBox(self.widget_13)
        self.cb_millesime_sirene.setObjectName("cb_millesime_sirene")
        self.gridLayout_4.addWidget(self.cb_millesime_sirene, 8, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_13)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_13)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_13)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.cb_millesime_adresse = QtWidgets.QComboBox(self.widget_13)
        self.cb_millesime_adresse.setObjectName("cb_millesime_adresse")
        self.gridLayout_4.addWidget(self.cb_millesime_adresse, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_13)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 6, 0, 1, 1)
        self.cb_millesime_insee = QtWidgets.QComboBox(self.widget_13)
        self.cb_millesime_insee.setObjectName("cb_millesime_insee")
        self.gridLayout_4.addWidget(self.cb_millesime_insee, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_13)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 6, 3, 1, 1)
        self.cb_millesime_inao = QtWidgets.QComboBox(self.widget_13)
        self.cb_millesime_inao.setObjectName("cb_millesime_inao")
        self.gridLayout_4.addWidget(self.cb_millesime_inao, 6, 4, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget_13)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_4.addWidget(self.checkBox_5, 10, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_13)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_4.addWidget(self.checkBox_4, 10, 1, 1, 1)
        self.pb_calcul_expert = QtWidgets.QPushButton(self.widget_13)
        self.pb_calcul_expert.setObjectName("pb_calcul_expert")
        self.gridLayout_4.addWidget(self.pb_calcul_expert, 10, 3, 1, 1)
        self.gridLayout_3.addWidget(self.widget_13, 0, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.onglet4_moda_calcul)
        self.widget_2.setGeometry(QtCore.QRect(20, 10, 971, 32))
        self.widget_2.setStyleSheet("QWidget{\n"
"    border:1px solid black;\n"
"    background-color: rgb(177, 177, 177);\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"    font-weight: bold;\n"
"    text-align:center;\n"
"    color: rgb(255, 85, 0);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_te_modacalcul = QtWidgets.QLabel(self.widget_2)
        self.lbl_te_modacalcul.setObjectName("lbl_te_modacalcul")
        self.horizontalLayout_5.addWidget(self.lbl_te_modacalcul)
        self.lbl_typealea_modacalcul = QtWidgets.QLabel(self.widget_2)
        self.lbl_typealea_modacalcul.setObjectName("lbl_typealea_modacalcul")
        self.horizontalLayout_5.addWidget(self.lbl_typealea_modacalcul)
        self.lbl_occ_modacalcul = QtWidgets.QLabel(self.widget_2)
        self.lbl_occ_modacalcul.setObjectName("lbl_occ_modacalcul")
        self.horizontalLayout_5.addWidget(self.lbl_occ_modacalcul)
        self.widget_8 = QtWidgets.QWidget(self.onglet4_moda_calcul)
        self.widget_8.setGeometry(QtCore.QRect(20, 480, 1021, 41))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(30)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(670, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pb_charger_couches_indicateurs = QtWidgets.QPushButton(self.widget_8)
        self.pb_charger_couches_indicateurs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pb_charger_couches_indicateurs.setObjectName("pb_charger_couches_indicateurs")
        self.horizontalLayout_7.addWidget(self.pb_charger_couches_indicateurs)
        self.w_conteneur_page_2 = QtWidgets.QWidget(self.onglet4_moda_calcul)
        self.w_conteneur_page_2.setGeometry(QtCore.QRect(20, 60, 1031, 31))
        self.w_conteneur_page_2.setObjectName("w_conteneur_page_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.w_conteneur_page_2)
        self.horizontalLayout_8.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.w_conteneur_page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.w_conteneur_page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_8.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.w_conteneur_page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_8.addWidget(self.label_38)
        self.w_conteneur_page_3 = QtWidgets.QWidget(self.onglet4_moda_calcul)
        self.w_conteneur_page_3.setGeometry(QtCore.QRect(20, 100, 1031, 371))
        self.w_conteneur_page_3.setObjectName("w_conteneur_page_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.w_conteneur_page_3)
        self.horizontalLayout_9.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.w_listing_fonctions_calcul = QtWidgets.QWidget(self.w_conteneur_page_3)
        self.w_listing_fonctions_calcul.setObjectName("w_listing_fonctions_calcul")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.w_listing_fonctions_calcul)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.w_listing_fonctions_calcul)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 314, 333))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lay_listing_fonctions_calcul = QtWidgets.QVBoxLayout()
        self.lay_listing_fonctions_calcul.setObjectName("lay_listing_fonctions_calcul")
        self.verticalLayout_6.addLayout(self.lay_listing_fonctions_calcul)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.addWidget(self.scrollArea_3)
        self.horizontalLayout_9.addWidget(self.w_listing_fonctions_calcul)
        self.w_listing_indicateurs_pt_vue = QtWidgets.QWidget(self.w_conteneur_page_3)
        self.w_listing_indicateurs_pt_vue.setObjectName("w_listing_indicateurs_pt_vue")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.w_listing_indicateurs_pt_vue)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.w_listing_indicateurs_pt_vue)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 313, 333))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.lay_listing_indicateurs_pt_vue = QtWidgets.QVBoxLayout()
        self.lay_listing_indicateurs_pt_vue.setObjectName("lay_listing_indicateurs_pt_vue")
        self.verticalLayout_20.addLayout(self.lay_listing_indicateurs_pt_vue)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_13.addWidget(self.scrollArea_5)
        self.horizontalLayout_9.addWidget(self.w_listing_indicateurs_pt_vue)
        self.w_listing_indicateurs = QtWidgets.QWidget(self.w_conteneur_page_3)
        self.w_listing_indicateurs.setObjectName("w_listing_indicateurs")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.w_listing_indicateurs)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.w_listing_indicateurs)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 314, 333))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lay_listing_indicateurs = QtWidgets.QVBoxLayout()
        self.lay_listing_indicateurs.setObjectName("lay_listing_indicateurs")
        self.verticalLayout_19.addLayout(self.lay_listing_indicateurs)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_14.addWidget(self.scrollArea_6)
        self.horizontalLayout_9.addWidget(self.w_listing_indicateurs)
        self.onglets.addWidget(self.onglet4_moda_calcul)
        self.onglet5_analyse_resultats = QtWidgets.QWidget()
        self.onglet5_analyse_resultats.setStyleSheet("*{\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    border:none;\n"
"    background-color: white;\n"
"    font: 14px \'Arial\';\n"
"    font-weight: bold;\n"
"    color: rgb(239, 120, 88);\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.54 rgba(251, 251, 251, 0), stop:0.541 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(251, 212, 81, 255);\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);    \n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgba(249,191,144,255);\n"
"    border-radius: 3px;\n"
"    border:2px outset rgb(239, 120, 88);\n"
"    color: rgba(41, 37, 116, 255);\n"
"    font: 11px \"Arial\";\n"
"    font-weight: bold;\n"
"    margin-left: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border:2px inset rgb(239, 120, 88);\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.54 rgba(251, 251, 251, 0), stop:0.541 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}\n"
"\n"
"\n"
"QRadioButtfon {\n"
"    background-color: rgb(252,254,252);\n"
"    color: black;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{ \n"
"    border: 1px solid; \n"
"    border-color: rgb(239, 120, 88);\n"
"    border-radius: 5px;\n"
"    background-color: white; \n"
"    width: 11px; \n"
"    height: 11px; \n"
"}\n"
"\n"
"QRadioButton::indicator::checked{ \n"
"    border: 3px solid; \n"
"    border-color: white;\n"
"    border-radius: 6px;\n"
"    background-color: rgba(41, 37, 116, 255);\n"
"    width: 7px; \n"
"    height: 7px; \n"
"}\n"
"\n"
"QCheckBox:pressed{\n"
"    border:2px inset rgb(239, 120, 88);\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);\n"
"    background-colorr: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.54 rgba(251, 251, 251, 0), stop:0.541 rgba(251, 212, 81, 255), stop:1 rgba(251, 212, 81, 255));\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked{ \n"
"    border: 1px solid; \n"
"    border-color: rgb(239, 120, 88);\n"
"    border-radius: 1px;\n"
"    background-color: white; \n"
"    width: 11px; \n"
"    height: 11px; \n"
"}\n"
"\n"
"QCheckBox::indicator::checked{ \n"
"    border: 3px solid; \n"
"    border-color: white;\n"
"    border-radius: 1px;\n"
"    background-color: rgba(41, 37, 116, 255);\n"
"    width: 7px; \n"
"    height: 7px; \n"
"}")
        self.onglet5_analyse_resultats.setObjectName("onglet5_analyse_resultats")
        self.gb_mise_en_forme_resultats = QtWidgets.QGroupBox(self.onglet5_analyse_resultats)
        self.gb_mise_en_forme_resultats.setGeometry(QtCore.QRect(20, 20, 300, 150))
        self.gb_mise_en_forme_resultats.setObjectName("gb_mise_en_forme_resultats")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_mise_en_forme_resultats)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.gb_mise_en_forme_resultats)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gb_mise_en_forme_resultats)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 0, 1, 1)
        self.pb_calcul_indic = QtWidgets.QPushButton(self.gb_mise_en_forme_resultats)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_calcul_indic.sizePolicy().hasHeightForWidth())
        self.pb_calcul_indic.setSizePolicy(sizePolicy)
        self.pb_calcul_indic.setObjectName("pb_calcul_indic")
        self.gridLayout.addWidget(self.pb_calcul_indic, 2, 0, 1, 1)
        self.gb_mise_en_forme_resultats_2 = QtWidgets.QGroupBox(self.onglet5_analyse_resultats)
        self.gb_mise_en_forme_resultats_2.setGeometry(QtCore.QRect(750, 20, 300, 150))
        self.gb_mise_en_forme_resultats_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gb_mise_en_forme_resultats_2.setObjectName("gb_mise_en_forme_resultats_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_mise_en_forme_resultats_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_6 = QtWidgets.QCheckBox(self.gb_mise_en_forme_resultats_2)
        self.checkBox_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gb_mise_en_forme_resultats_2)
        self.checkBox_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.pushButton_15 = QtWidgets.QPushButton(self.gb_mise_en_forme_resultats_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout.addWidget(self.pushButton_15)
        self.widget_3 = QtWidgets.QWidget(self.onglet5_analyse_resultats)
        self.widget_3.setGeometry(QtCore.QRect(20, 180, 1030, 521))
        self.widget_3.setObjectName("widget_3")
        self.w_dashboard = QtWidgets.QWidget(self.widget_3)
        self.w_dashboard.setGeometry(QtCore.QRect(0, 0, 1030, 450))
        self.w_dashboard.setObjectName("w_dashboard")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.w_dashboard)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 1030, 450))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1030, 450))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.dashboards = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_2)
        self.dashboards.setGeometry(QtCore.QRect(0, 20, 1030, 430))
        self.dashboards.setStyleSheet("*{\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    border:none;\n"
"    background-color: white;\n"
"    font: 14px \'Arial\';\n"
"    font-weight: bold;\n"
"    color: rgb(239, 120, 88);\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"    border-bottom:1px dashed rgb(239, 120, 88);\n"
"    font-weight: bold;\n"
"    font: 75 17pt \"Arial\";\n"
"    color: rgb(239, 120, 88);\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(251, 212, 81, 255);\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);    \n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:white;\n"
"    borderr: 1px solid rgba(251, 212, 81, 255);\n"
"    border: none;\n"
"    border-radius:15px;\n"
"    margin:0px;\n"
"    font: 12px \"Arial\";\n"
"    font-weight: bold;\n"
"    color: rgba(41, 37, 116, 255);    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border:2px inset rgb(239, 120, 88);\n"
"}\n"
"\n"
"\n"
"")
        self.dashboards.setObjectName("dashboards")
        self.db_sngri = QtWidgets.QWidget()
        self.db_sngri.setObjectName("db_sngri")
        self.label_28 = QtWidgets.QLabel(self.db_sngri)
        self.label_28.setGeometry(QtCore.QRect(10, 0, 300, 31))
        self.label_28.setStyleSheet("")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.db_sngri)
        self.label_29.setGeometry(QtCore.QRect(370, 0, 300, 31))
        self.label_29.setStyleSheet("")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.db_sngri)
        self.label_30.setGeometry(QtCore.QRect(720, 0, 300, 31))
        self.label_30.setStyleSheet("")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.pb_sngri_s3_1a = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s3_1a.setGeometry(QtCore.QRect(30, 50, 250, 100))
        self.pb_sngri_s3_1a.setObjectName("pb_sngri_s3_1a")
        self.pb_sngri_s1_2a = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s1_2a.setGeometry(QtCore.QRect(30, 180, 250, 100))
        self.pb_sngri_s1_2a.setObjectName("pb_sngri_s1_2a")
        self.pb_sngri_s1_2b = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s1_2b.setGeometry(QtCore.QRect(30, 310, 250, 100))
        self.pb_sngri_s1_2b.setObjectName("pb_sngri_s1_2b")
        self.pb_sngri_s2_2a = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s2_2a.setGeometry(QtCore.QRect(390, 50, 250, 80))
        self.pb_sngri_s2_2a.setObjectName("pb_sngri_s2_2a")
        self.pb_sngri_s2_6a = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s2_6a.setGeometry(QtCore.QRect(390, 150, 250, 80))
        self.pb_sngri_s2_6a.setObjectName("pb_sngri_s2_6a")
        self.pb_sngri_s2_14a = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s2_14a.setGeometry(QtCore.QRect(390, 260, 250, 150))
        self.pb_sngri_s2_14a.setObjectName("pb_sngri_s2_14a")
        self.pb_sngri_s3_1abis = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s3_1abis.setGeometry(QtCore.QRect(750, 50, 250, 80))
        self.pb_sngri_s3_1abis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pb_sngri_s3_1abis.setObjectName("pb_sngri_s3_1abis")
        self.pb_sngri_s3_1f = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s3_1f.setGeometry(QtCore.QRect(750, 150, 250, 80))
        self.pb_sngri_s3_1f.setObjectName("pb_sngri_s3_1f")
        self.pb_sngri_s3_2b = QtWidgets.QPushButton(self.db_sngri)
        self.pb_sngri_s3_2b.setGeometry(QtCore.QRect(750, 260, 250, 150))
        self.pb_sngri_s3_2b.setObjectName("pb_sngri_s3_2b")
        self.dashboards.addWidget(self.db_sngri)
        self.db_amenagement = QtWidgets.QWidget()
        self.db_amenagement.setObjectName("db_amenagement")
        self.pb_sngri_s3_1abis_2 = QtWidgets.QPushButton(self.db_amenagement)
        self.pb_sngri_s3_1abis_2.setGeometry(QtCore.QRect(390, 250, 250, 80))
        self.pb_sngri_s3_1abis_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pb_sngri_s3_1abis_2.setObjectName("pb_sngri_s3_1abis_2")
        self.pb_sngri_s1_2a_2 = QtWidgets.QPushButton(self.db_amenagement)
        self.pb_sngri_s1_2a_2.setGeometry(QtCore.QRect(30, 250, 250, 150))
        self.pb_sngri_s1_2a_2.setObjectName("pb_sngri_s1_2a_2")
        self.label_31 = QtWidgets.QLabel(self.db_amenagement)
        self.label_31.setGeometry(QtCore.QRect(370, 0, 300, 31))
        self.label_31.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.pb_sngri_s2_14a_2 = QtWidgets.QPushButton(self.db_amenagement)
        self.pb_sngri_s2_14a_2.setGeometry(QtCore.QRect(750, 50, 250, 150))
        self.pb_sngri_s2_14a_2.setObjectName("pb_sngri_s2_14a_2")
        self.pb_sngri_s3_2b_2 = QtWidgets.QPushButton(self.db_amenagement)
        self.pb_sngri_s3_2b_2.setGeometry(QtCore.QRect(750, 260, 250, 150))
        self.pb_sngri_s3_2b_2.setObjectName("pb_sngri_s3_2b_2")
        self.pb_sngri_s2_2a_2 = QtWidgets.QPushButton(self.db_amenagement)
        self.pb_sngri_s2_2a_2.setGeometry(QtCore.QRect(390, 50, 250, 80))
        self.pb_sngri_s2_2a_2.setObjectName("pb_sngri_s2_2a_2")
        self.pb_sngri_s2_6a_2 = QtWidgets.QPushButton(self.db_amenagement)
        self.pb_sngri_s2_6a_2.setGeometry(QtCore.QRect(390, 150, 250, 80))
        self.pb_sngri_s2_6a_2.setObjectName("pb_sngri_s2_6a_2")
        self.label_32 = QtWidgets.QLabel(self.db_amenagement)
        self.label_32.setGeometry(QtCore.QRect(10, 0, 300, 31))
        self.label_32.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.pb_sngri_s3_1a_2 = QtWidgets.QPushButton(self.db_amenagement)
        self.pb_sngri_s3_1a_2.setGeometry(QtCore.QRect(30, 50, 250, 150))
        self.pb_sngri_s3_1a_2.setObjectName("pb_sngri_s3_1a_2")
        self.label_33 = QtWidgets.QLabel(self.db_amenagement)
        self.label_33.setGeometry(QtCore.QRect(720, 0, 300, 31))
        self.label_33.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.dashboards.addWidget(self.db_amenagement)
        self.db_crise = QtWidgets.QWidget()
        self.db_crise.setObjectName("db_crise")
        self.pb_sngri_s3_1abis_2 = QtWidgets.QPushButton(self.db_crise)
        self.pb_sngri_s3_1abis_2.setGeometry(QtCore.QRect(390, 250, 250, 80))
        self.pb_sngri_s3_1abis_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pb_sngri_s3_1abis_2.setObjectName("pb_sngri_s3_1abis_2")
        self.pb_sngri_s3_2b_2 = QtWidgets.QPushButton(self.db_crise)
        self.pb_sngri_s3_2b_2.setGeometry(QtCore.QRect(750, 260, 250, 150))
        self.pb_sngri_s3_2b_2.setObjectName("pb_sngri_s3_2b_2")
        self.dashboards.addWidget(self.db_crise)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.widget_16 = QtWidgets.QWidget(self.widget_3)
        self.widget_16.setGeometry(QtCore.QRect(10, 460, 1010, 50))
        self.widget_16.setObjectName("widget_16")
        self.label_26 = QtWidgets.QLabel(self.widget_16)
        self.label_26.setGeometry(QtCore.QRect(960, 30, 30, 16))
        self.label_26.setObjectName("label_26")
        self.label_2 = QtWidgets.QLabel(self.widget_16)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 30, 16))
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(self.widget_16)
        self.label_13.setGeometry(QtCore.QRect(466, 30, 30, 16))
        self.label_13.setObjectName("label_13")
        self.horizontalSlider = QtWidgets.QSlider(self.widget_16)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 10, 955, 22))
        self.horizontalSlider.setProperty("value", 18)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_12 = QtWidgets.QLabel(self.widget_16)
        self.label_12.setGeometry(QtCore.QRect(269, 30, 30, 16))
        self.label_12.setObjectName("label_12")
        self.label_22 = QtWidgets.QLabel(self.widget_16)
        self.label_22.setGeometry(QtCore.QRect(368, 30, 30, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_16)
        self.label_23.setGeometry(QtCore.QRect(565, 30, 30, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_16)
        self.label_24.setGeometry(QtCore.QRect(664, 30, 30, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widget_16)
        self.label_25.setGeometry(QtCore.QRect(762, 30, 30, 16))
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.widget_16)
        self.label_27.setGeometry(QtCore.QRect(861, 30, 30, 16))
        self.label_27.setObjectName("label_27")
        self.label_34 = QtWidgets.QLabel(self.widget_16)
        self.label_34.setGeometry(QtCore.QRect(90, 30, 30, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.widget_16)
        self.label_35.setGeometry(QtCore.QRect(10, 30, 30, 16))
        self.label_35.setObjectName("label_35")
        self.w_titre_dashboard = QtWidgets.QWidget(self.onglet5_analyse_resultats)
        self.w_titre_dashboard.setGeometry(QtCore.QRect(340, 10, 380, 150))
        self.w_titre_dashboard.setObjectName("w_titre_dashboard")
        self.label = QtWidgets.QLabel(self.w_titre_dashboard)
        self.label.setGeometry(QtCore.QRect(0, 0, 380, 31))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lbl_choix_terr_etude_3 = QtWidgets.QLabel(self.w_titre_dashboard)
        self.lbl_choix_terr_etude_3.setGeometry(QtCore.QRect(40, 60, 150, 20))
        self.lbl_choix_terr_etude_3.setObjectName("lbl_choix_terr_etude_3")
        self.cbox_niv_synthese = QtWidgets.QComboBox(self.w_titre_dashboard)
        self.cbox_niv_synthese.setGeometry(QtCore.QRect(165, 60, 185, 20))
        self.cbox_niv_synthese.setAutoFillBackground(False)
        self.cbox_niv_synthese.setEditable(False)
        self.cbox_niv_synthese.setMaxVisibleItems(20)
        self.cbox_niv_synthese.setObjectName("cbox_niv_synthese")
        self.cbox_niv_synthese.addItem("")
        self.lbl_choix_terr_etude_4 = QtWidgets.QLabel(self.w_titre_dashboard)
        self.lbl_choix_terr_etude_4.setGeometry(QtCore.QRect(40, 120, 60, 20))
        self.lbl_choix_terr_etude_4.setObjectName("lbl_choix_terr_etude_4")
        self.cbox_secteur_etude = QtWidgets.QComboBox(self.w_titre_dashboard)
        self.cbox_secteur_etude.setGeometry(QtCore.QRect(100, 120, 250, 20))
        self.cbox_secteur_etude.setAutoFillBackground(False)
        self.cbox_secteur_etude.setEditable(False)
        self.cbox_secteur_etude.setMaxVisibleItems(20)
        self.cbox_secteur_etude.setObjectName("cbox_secteur_etude")
        self.cbox_secteur_etude.addItem("")
        self.onglets.addWidget(self.onglet5_analyse_resultats)
        self.onglet6_actions_reduction = QtWidgets.QWidget()
        self.onglet6_actions_reduction.setObjectName("onglet6_actions_reduction")
        self.w_conteneur_glob_actions = QtWidgets.QWidget(self.onglet6_actions_reduction)
        self.w_conteneur_glob_actions.setGeometry(QtCore.QRect(0, 50, 1070, 670))
        self.w_conteneur_glob_actions.setObjectName("w_conteneur_glob_actions")
        self.pb_connaitre = QtWidgets.QPushButton(self.onglet6_actions_reduction)
        self.pb_connaitre.setGeometry(QtCore.QRect(80, 10, 75, 23))
        self.pb_connaitre.setObjectName("pb_connaitre")
        self.pb_agir = QtWidgets.QPushButton(self.onglet6_actions_reduction)
        self.pb_agir.setGeometry(QtCore.QRect(170, 10, 75, 23))
        self.pb_agir.setObjectName("pb_agir")
        self.onglets.addWidget(self.onglet6_actions_reduction)
        self.onglet7_suivi_actions = QtWidgets.QWidget()
        self.onglet7_suivi_actions.setObjectName("onglet7_suivi_actions")
        self.widget_12 = QtWidgets.QWidget(self.onglet7_suivi_actions)
        self.widget_12.setGeometry(QtCore.QRect(210, 20, 571, 351))
        self.widget_12.setStyleSheet("image: url(:/plugins/plugin_agirisk/medias/Exemple_graphique_avancement_actions.gif);")
        self.widget_12.setObjectName("widget_12")
        self.onglets.addWidget(self.onglet7_suivi_actions)
        self.onglet8_aide = QtWidgets.QWidget()
        self.onglet8_aide.setObjectName("onglet8_aide")
        self.te_notice_indicateurs_6 = QtWidgets.QTextEdit(self.onglet8_aide)
        self.te_notice_indicateurs_6.setGeometry(QtCore.QRect(30, 20, 241, 111))
        self.te_notice_indicateurs_6.setObjectName("te_notice_indicateurs_6")
        self.mode_expert = QtWidgets.QCheckBox(self.onglet8_aide)
        self.mode_expert.setGeometry(QtCore.QRect(30, 150, 111, 18))
        self.mode_expert.setChecked(False)
        self.mode_expert.setObjectName("mode_expert")
        self.tb_logo_utilisateur = QtWidgets.QToolButton(self.onglet8_aide)
        self.tb_logo_utilisateur.setEnabled(False)
        self.tb_logo_utilisateur.setGeometry(QtCore.QRect(146, 200, 61, 22))
        self.tb_logo_utilisateur.setObjectName("tb_logo_utilisateur")
        self.w_logo_utilisateur = QtWidgets.QWidget(self.onglet8_aide)
        self.w_logo_utilisateur.setEnabled(False)
        self.w_logo_utilisateur.setGeometry(QtCore.QRect(250, 190, 81, 61))
        self.w_logo_utilisateur.setObjectName("w_logo_utilisateur")
        self.label_3 = QtWidgets.QLabel(self.w_logo_utilisateur)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lbl_nveau_terr_etude_3 = QtWidgets.QLabel(self.onglet8_aide)
        self.lbl_nveau_terr_etude_3.setEnabled(False)
        self.lbl_nveau_terr_etude_3.setGeometry(QtCore.QRect(40, 200, 91, 20))
        self.lbl_nveau_terr_etude_3.setObjectName("lbl_nveau_terr_etude_3")
        self.onglets.addWidget(self.onglet8_aide)
        self.verticalLayout_2.addWidget(self.onglets)
        self.verticalLayout_3.addWidget(self.central_container)
        self.horizontalLayout_2.addWidget(self.main_body)

        self.retranslateUi(Dialog)
        self.onglets.setCurrentIndex(3)
        self.dashboards.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AgiRisk - Amélioration de la Gestion Individualisée de la Résilience aux Inondations des Systèmes territoriaux"))
        self.menu_accueil.setText(_translate("Dialog", "ACCUEIL"))
        self.menu_terr_etude.setText(_translate("Dialog", "TERRITOIRE"))
        self.menu_choix_indic.setText(_translate("Dialog", "INDICATEURS"))
        self.menu_moda_calcul.setText(_translate("Dialog", "MODALITES \n"
" DE CALCUL"))
        self.menu_diag.setText(_translate("Dialog", "\n"
"ANALYSE\n"
""))
        self.menu_actions_reduc.setText(_translate("Dialog", "ACTIONS"))
        self.menu_suivi_actions.setText(_translate("Dialog", "SUIVI"))
        self.menu_aide.setText(_translate("Dialog", "AIDE"))
        self.label_6.setText(_translate("Dialog", "Choix du territoire et des aléas"))
        self.accueil_terr_etude.setText(_translate("Dialog", "TERRITOIRE"))
        self.pb_etape3_3.setText(_translate("Dialog", "1"))
        self.label_7.setText(_translate("Dialog", "Choix des indicateurs et modalités de calcul"))
        self.accueil_choix_indic.setText(_translate("Dialog", "PERSONNALISATION"))
        self.pb_etape3_2.setText(_translate("Dialog", "2"))
        self.label_8.setText(_translate("Dialog", "du diagnostic de vulnérabilité"))
        self.accueil_diag.setText(_translate("Dialog", "ANALYSE"))
        self.pb_etape3.setText(_translate("Dialog", "3"))
        self.label_9.setText(_translate("Dialog", "pour réduire la vulnérabilité"))
        self.accueil_actions_reduc.setText(_translate("Dialog", "ACTIONS"))
        self.pb_etape4.setText(_translate("Dialog", "4"))
        self.accueil_suivi_actions.setText(_translate("Dialog", "SUIVI"))
        self.pb_etape5.setText(_translate("Dialog", "5"))
        self.label_10.setText(_translate("Dialog", "de l\'évolution de la vulnérabilité"))
        self.gb_terr_etude.setTitle(_translate("Dialog", "Territoire d\'étude et aléa considéré"))
        self.cbox_terr_etude.setItemText(0, _translate("Dialog", "Sélectionner votre territoire"))
        self.gb_emprise_carto.setTitle(_translate("Dialog", "Emprise cartographique (carte)"))
        self.selection_territoire_etude.setText(_translate("Dialog", "Nouveau territoire"))
        self.lbl_choix_terr_etude_2.setText(_translate("Dialog", "Occurrence : "))
        self.cbox_couche_alea.setItemText(0, _translate("Dialog", "Liste des couches d\'aléas disponibles"))
        self.cbox_couche_alea.setItemText(1, _translate("Dialog", "Zip Zich"))
        self.cbox_couche_alea.setItemText(2, _translate("Dialog", "PPRi"))
        self.lbl_choix_terr_etude.setText(_translate("Dialog", "Territoire :"))
        self.cbox_type_alea.setCurrentText(_translate("Dialog", "Liste des couches d\'aléas disponibles"))
        self.cbox_type_alea.setItemText(0, _translate("Dialog", "Liste des couches d\'aléas disponibles"))
        self.cbox_type_alea.setItemText(1, _translate("Dialog", "Zip Zich"))
        self.cbox_type_alea.setItemText(2, _translate("Dialog", "PPRi"))
        self.lbl_choix_type_alea.setText(_translate("Dialog", "Type aléa :"))
        self.selection_alea.setText(_translate("Dialog", "Nouvelle couche d\'aléa"))
        self.gb_choix_pt_de_vue.setTitle(_translate("Dialog", "Choix du point de vue"))
        self.pb_nvelle_arborescence.setText(_translate("Dialog", "Personnaliser une \n"
"nouvelle arborescence"))
        self.gb_thematiques.setTitle(_translate("Dialog", "Thématiques et centres d\'intérêt"))
        self.pb_valider_thematiques.setText(_translate("Dialog", "Ok"))
        self.chkb_gestion_crise.setText(_translate("Dialog", "Gestion de crise"))
        self.chkb_amenagt_terr.setText(_translate("Dialog", "Aménagement du territoire"))
        self.chkb_act_economique.setText(_translate("Dialog", "Activité économique"))
        self.chkb_environnement.setText(_translate("Dialog", "Environnement"))
        self.gb_choix_indic.setTitle(_translate("Dialog", "Sélection des indicateurs : "))
        self.pb_indic_retenu.setText(_translate("Dialog", "à calculer"))
        self.pb_indic_ecarte.setText(_translate("Dialog", "à écarter"))
        self.te_notice_indicateurs_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:8; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">Modalités de calcul :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">- indiquer un lien vers la doc</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">+ faire un résumé</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">NB : dans la fonction postgis, on calcule toutes les données ( absolu, pourcentage1, pourcentage2, ...) et c\'est le plugin qui choisit qu\'est-ce qui est affiché</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">+ lister les données sources disponibles</span></p></body></html>"))
        self.te_notice_indicateurs_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:8; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">Disponibilité des données sources :</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">Prévoir une page de vérification de la bonne disponibilité des données sources, avec lien pour l\'utilisateur pour charger sa propre donnée. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">Prévoir bouton aide à l\'import des données manquantes</span></p></body></html>"))
        self.te_notice_indicateurs_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:8; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">Listing en arborescence des indicateurs</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\">Icônes à droite de l\'indicateur : coche verte si modalité de calcul déjà choisie par l\'utilisateur, point d\'interrogation si choix à faire, icône à définir si choix par défaut sans autre alternative, ...</span></p></body></html>"))
        self.gb_mise_en_forme_resultats_3.setTitle(_translate("Dialog", "Calcul des variables & indicateurs"))
        self.label_16.setText(_translate("Dialog", "BD TOPO"))
        self.label_20.setText(_translate("Dialog", "Sirene"))
        self.label_15.setText(_translate("Dialog", "RPG"))
        self.label_14.setText(_translate("Dialog", "GPU"))
        self.label_17.setText(_translate("Dialog", "Adresse premium"))
        self.label_18.setText(_translate("Dialog", "INSEE"))
        self.label_19.setText(_translate("Dialog", "Inao"))
        self.checkBox_5.setText(_translate("Dialog", "(Re)calcul des indicateurs"))
        self.checkBox_4.setText(_translate("Dialog", "Affichage des couches dans Qgis"))
        self.pb_calcul_expert.setText(_translate("Dialog", "Lancer le calcul"))
        self.lbl_te_modacalcul.setText(_translate("Dialog", "Territoire d\'étude : "))
        self.lbl_typealea_modacalcul.setText(_translate("Dialog", "Type d\'aléa : "))
        self.lbl_occ_modacalcul.setText(_translate("Dialog", "Occurence : "))
        self.pb_charger_couches_indicateurs.setText(_translate("Dialog", "Charger les couches sélectionnées"))
        self.label_36.setText(_translate("Dialog", "Fonctions de calcul disponibles"))
        self.label_37.setText(_translate("Dialog", "Indicateurs du point de vue"))
        self.label_38.setText(_translate("Dialog", "Couches du schéma p_rep_carto"))
        self.gb_mise_en_forme_resultats.setTitle(_translate("Dialog", "Calcul des indicateurs"))
        self.checkBox.setText(_translate("Dialog", "Affichage des couches dans Qgis"))
        self.checkBox_2.setText(_translate("Dialog", "(Re)calcul des indicateurs"))
        self.pb_calcul_indic.setText(_translate("Dialog", "Charger l\'analyse \n"
"cartographique"))
        self.gb_mise_en_forme_resultats_2.setTitle(_translate("Dialog", "Documents de synthèse"))
        self.checkBox_6.setText(_translate("Dialog", "Générer carte par indicateur"))
        self.checkBox_7.setText(_translate("Dialog", "Générer carte de synthèse "))
        self.pushButton_15.setText(_translate("Dialog", "Générer cartes du \n"
"composeur d\'impression"))
        self.label_28.setText(_translate("Dialog", "Sécurité des personnes"))
        self.label_29.setText(_translate("Dialog", "Coût des dommages"))
        self.label_30.setText(_translate("Dialog", "Retour à la normale"))
        self.pb_sngri_s3_1a.setText(_translate("Dialog", "Personnes en zone inondable"))
        self.pb_sngri_s1_2a.setText(_translate("Dialog", "Population dans des bâtiments \n"
"de plain pied fortement inondables"))
        self.pb_sngri_s1_2b.setText(_translate("Dialog", "Population dans des locaux de \n"
"plain pied fortement inondables"))
        self.pb_sngri_s2_2a.setText(_translate("Dialog", "Coût des dommages aux logements"))
        self.pb_sngri_s2_6a.setText(_translate("Dialog", "Coût des dommages aux cultures"))
        self.pb_sngri_s2_14a.setText(_translate("Dialog", "Surfaces \'A Urbaniser\'"))
        self.pb_sngri_s3_1abis.setText(_translate("Dialog", "Personnes en zone inondable"))
        self.pb_sngri_s3_1f.setText(_translate("Dialog", "Surfaces agricoles inondables"))
        self.pb_sngri_s3_2b.setText(_translate("Dialog", "Capacités d\'hébergement"))
        self.pb_sngri_s3_1abis_2.setText(_translate("Dialog", "Emplois en zone inondable"))
        self.pb_sngri_s1_2a_2.setText(_translate("Dialog", "Montant des dommages aux logements"))
        self.label_31.setText(_translate("Dialog", "Economie"))
        self.pb_sngri_s2_14a_2.setText(_translate("Dialog", "Surfaces A Urbaniser"))
        self.pb_sngri_s3_2b_2.setText(_translate("Dialog", "Capacités d\'hébergement"))
        self.pb_sngri_s2_2a_2.setText(_translate("Dialog", "Montant des dommages aux cultures"))
        self.pb_sngri_s2_6a_2.setText(_translate("Dialog", "Montant des dommages aux entreprises"))
        self.label_32.setText(_translate("Dialog", "Population"))
        self.label_40.setText(_translate("Dialog", "Population"))
        self.pb_sngri_s3_1a_2.setText(_translate("Dialog", "Logements en zone inondable"))
        self.label_33.setText(_translate("Dialog", "Action publique"))
        self.label_41.setText(_translate("Dialog", "Action publique"))
        self.label_26.setText(_translate("Dialog", "2100"))
        self.label_2.setText(_translate("Dialog", "2020"))
        self.label_13.setText(_translate("Dialog", "2050"))
        self.label_12.setText(_translate("Dialog", "2030"))
        self.label_22.setText(_translate("Dialog", "2040"))
        self.label_23.setText(_translate("Dialog", "2060"))
        self.label_24.setText(_translate("Dialog", "2070"))
        self.label_25.setText(_translate("Dialog", "2080"))
        self.label_27.setText(_translate("Dialog", "2090"))
        self.label_34.setText(_translate("Dialog", "2010"))
        self.label_35.setText(_translate("Dialog", "2000"))
        self.label.setText(_translate("Dialog", "Tableau de bord"))
        self.lbl_choix_terr_etude_3.setText(_translate("Dialog", "Echelle de synthèse : "))
        self.cbox_niv_synthese.setItemText(0, _translate("Dialog", "Commune"))
        self.lbl_choix_terr_etude_4.setText(_translate("Dialog", "Secteur :"))
        self.cbox_secteur_etude.setItemText(0, _translate("Dialog", "Sélectionner le secteur d\'étude"))
        self.pb_connaitre.setText(_translate("Dialog", "Connaître"))
        self.pb_agir.setText(_translate("Dialog", "Agir"))
        self.te_notice_indicateurs_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:8; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Prévoir démarche maintenance avec version python / QGis et compatibilité du plugin / Notes de version. </p></body></html>"))
        self.mode_expert.setText(_translate("Dialog", "Mode expert"))
        self.tb_logo_utilisateur.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "Logo"))
        self.lbl_nveau_terr_etude_3.setText(_translate("Dialog", "Logo(s) utilisateur : "))
from qgis.gui import QgsMapCanvas
import resources_rc
